version: '3'

services:
  ve-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: ve-api
    restart: unless-stopped
    networks:
      - common_traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.ve-api.rule=Host(`votingescrow.equilibrefinance.com`)
      - traefik.http.routers.ve-api.tls.certresolver=letsencrypt
      - traefik.http.routers.ve-api.entryPoints=https
      - traefik.http.services.ve-api.loadbalancer.server.port=8381
      - traefik.docker.network=common_traefik
    volumes:
      - ./data:/data
      - /app/node_modules
networks:
  common_traefik:
    external: true
