version: '3'

services:
  ve-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: ve-api
    restart: unless-stopped
    expose:
      - 8381:8381
    volumes:
      - ./data:/app/data
